language: node_js
node_js: "12"

cache:
  yarn: true

stages:
  - Test
  - name: Release
    if: repo = "SocialGouv/postgrester" AND tag IS present

jobs:
  include:
    - stage: Test
      name: Unit Tests
      script: ./scripts/ci/run_unit_tests.sh

    - stage: Release
      name: Github Release
      script: skip
      before_deploy:
        - yarn ci:generate:release_notes
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        edge:
          branch: master
        release_notes_file: ./RELEASE_NOTES.md
        on:
          repo: SocialGouv/postgrester
          tags: true

    - stage: Release
      name: NPM Package
      script: skip
      before_deploy:
        - yarn build
      deploy:
        provider: npm
        access: public
        api_key: $NPM_TOKEN
        edge:
          branch: master
        email: ivan.gabriele@gmail.com
        on:
          repo: SocialGouv/postgrester
          tags: true

notifications:
  email:
    on_failure: change
    on_success: never
