language: node_js

cache:
  yarn: true

stages:
  - Test
  - name: Release
    if: repo = "SocialGouv/postgrester" AND tag IS present

jobs:
  include:
    - stage: Test
      name: Unit Tests (v10)
      node_js: "10"
      install: yarn --frozen-lockfile
    - stage: Test
      name: Unit Tests (v12)
      node_js: "12"
      install: yarn --frozen-lockfile
      after_script: ./node_modules/.bin/coveralls < ./coverage/lcov.info

    - stage: Release
      name: Github Release
      node_js: "12"
      script: skip
      before_deploy:
        - yarn build:release
        - yarn ci:generate:release_notes
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        edge:
          branch: master
        file: ./postgrester-unsigned.zip
        release_notes_file: ./RELEASE_NOTES.md
        on:
          repo: SocialGouv/postgrester
          tags: true

    - stage: Release
      name: NPM Package
      script: skip
      before_deploy:
        - yarn build
      deploy:
        provider: npm
        access: public
        api_key: $NPM_TOKEN
        edge:
          branch: master
        email: ivan.gabriele@gmail.com
        on:
          repo: SocialGouv/postgrester
          tags: true

# Limit branches builds to "master" & "develop" ones:
branches:
  only:
    - develop
    - master
    - /^v\d+\.\d+\.\d+(-(alpha|beta)\.\d+)?$/

notifications:
  email:
    on_failure: change
    on_success: never
