version: "3"

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: test_db_password
      POSTGRES_USER: test_db_user
    volumes:
      - postgre-data:/var/lib/postgresql/data

  # https://postgrest.org/en/stable/install.html#containerized-postgrest-and-db-with-docker-compose
  postgrest:
    image: "postgrest/postgrest:${POSTGREST_VERSION}"
    restart: always
    ports:
      - 3000:3000
    environment:
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_DB_SCHEMA: api
      PGRST_DB_URI: postgresql://test_db_user:test_db_password@db:5432/test_db
    depends_on:
      - db

volumes:
  postgre-data:
