name: Check

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - run: yarn
      - run: yarn test:lint

  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - run: yarn
      - run: yarn test:unit
      - run: yarn codecov

  e2e_test:
    name: E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        POSTGREST_VERSION: ["v8.0.0.20211102", "v9.0.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - run: yarn
      - run: yarn setup
        env:
          POSTGREST_VERSION: ${{ matrix.POSTGREST_VERSION }}
      - run: docker ps
      - run: yarn test:e2e
