name: Test & Publish

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
      - run: yarn
      - run: yarn test:lint

  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
      - run: yarn
      - run: yarn test:unit
      - run: yarn codecov

  e2e_test:
    name: E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        POSTGREST_VERSION: ["v8.0.0.20211102", "v9.0.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
      - run: yarn
      - run: yarn setup
        env:
          POSTGREST_VERSION: ${{ matrix.POSTGREST_VERSION }}
      - run: docker ps
      - run: yarn test:e2e

  publish:
    name: Publish
    if: ${{ contains(github.ref, 'refs/tags/') }}
    needs: [lint, unit_test, e2e_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    name: Release
    if: ${{ contains(github.ref, 'refs/tags/') }}
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
      - run: yarn
      - run: yarn build:release
      - run: yarn ci:generate:release_notes
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./postgrester-unsigned.zip"
          bodyFile: "./RELEASE_NOTES.md"
          token: ${{ secrets.GITHUB_TOKEN }}
